### ISSUE TITLE
Build directories not being created

### ISSUE THREAD

**Issue by RawrbearHS** [AE-Hopscotch/builder-extension#1]
`npm run build` fails because the `build/chrome/` and `build/firefox/` directories are not generated if they do not exist.

Creating these directories manually is a workaround for this issue.

**Comment by AE-Hopscotch** [comment]
Fixed in the [latest release](https://github.com/AE-Hopscotch/builder-extension/releases/tag/v1.0.0-beta.2) (see changelog)
Commit: https://github.com/AE-Hopscotch/builder-extension/commit/7d6d2cdf1e6078c1c1142cdfb49888d95065e127

---
You should also be able to use the provided releases for both Chromium-based browsers and Firefox now!
